import './globals.css';

import { Kanit, Lexend } from 'next/font/google';

const kanit = Kanit({
  weight: ['700', '600', '500', '400'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-kanit',
});

const lexend = Lexend({
  weight: ['700', '600', '500', '400', '300'],
  style: 'normal',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-lexend',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${kanit.variable} ${lexend.variable}`}>
      <body className="font-kanitFont">
        {children}
        <div id="modal-root"></div>
      </body>
    </html>
  );
}
