import './globals.css';

import { Kanit, Lexend } from 'next/font/google';

import { Navbar } from '@/components/layout/Navbar';

const kanit = Kanit({
  weight: ['700', '600'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-kanit',
});

const lexend = Lexend({
  weight: ['600', '500', '300'],
  style: 'normal',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-lexend',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${kanit.variable} ${lexend.variable}`}>
      <body className="bg-LoginBg bg-no-repeat font-kanitFont">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
